set encoding=utf8
colorscheme elflord
syn on
set ai
set ruler
set hlsearch

set modelines=0
set nomodeline

autocmd BufNewFile,BufRead * setlocal formatoptions-=r formatoptions-=c formatoptions-=o 

highlight CursorLine cterm=NONE

" highlight trailing whitespace
highlight WhitespaceEOL ctermbg=red guibg=red
autocmd BufRead,BufNew * match WhitespaceEOL /\s\+$/

set backspace=2


" xsel integration
command! -range Xc <line1>,<line2>call XSelCopy()
function! XSelCopy()
	echo system("xsel -ib", join(getline(a:firstline, a:lastline),"\n"))
endfunction

command! Xp call XSelPaste()
function! XSelPaste()
	r!xsel -b
endfunction



" insert <file>:<line> into yank buffer - Bp for bufferposition or breakpoint :)
command! Bp call BufferPosition()
function! BufferPosition()
	let @" = @% . ":" . line('.')
endfunction



" holy war follows
command! Ts call SwitchToTabIsSpaces()
function! SwitchToTabIsSpaces()
	set shiftwidth=4
	set tabstop=13
	set softtabstop=4
	set expandtab
endfunction

command! Tt call SwitchToTabIsTabs()
function! SwitchToTabIsTabs()
	set shiftwidth=8
	set tabstop=8
	set softtabstop=0
	set noexpandtab
endfunction

command! Tt4 call SwitchToTabIsTabsWidth4()
function! SwitchToTabIsTabsWidth4()
	set shiftwidth=4
	set tabstop=4
	set softtabstop=0
	set noexpandtab
endfunction

