set encoding=utf8
colorscheme elflord
syn on
set ai
set ruler
set hlsearch

set modelines=0
set nomodeline

autocmd BufNewFile,BufRead * setlocal formatoptions-=r formatoptions-=c formatoptions-=o

highlight CursorLine cterm=NONE

" highlight trailing whitespace
highlight WhitespaceEOL ctermbg=red guibg=red
autocmd BufRead,BufNew * match WhitespaceEOL /\s\+$/

" :Whatever; turns off highlight of trailing whitespace
command! Whatever call Whatever()
function! Whatever()
	highlight clear WhitespaceEOL
endfunction

set backspace=2


" disable help via F1 (:help is fine!)
nmap <F1> <nop>

" OS detection
let g:os = substitute(system('uname'), '\n', '', '')

" xsel integration
command! -range Xc <line1>,<line2>call XSelCopy()
function! XSelCopy()
	if g:os == "Linux"
		echo system("xsel -ib", join(getline(a:firstline, a:lastline),"\n"))
	elseif g:os == "Darwin"
		echo system("pbcopy", join(getline(a:firstline, a:lastline),"\n"))
	endif
endfunction

command! Xp call XSelPaste()
function! XSelPaste()
	if g:os == "Linux"
		r!xsel -b
	elseif g:os == "Darwin"
		r!pbpaste
	endif
endfunction



" insert <file>:<line> into yank buffer - Bp for bufferposition or breakpoint :)
command! Bp call BufferPosition()
function! BufferPosition()
	let @" = @% . ":" . line('.')
endfunction


" insert YYYY-MM-DD
command! D call PutDate()
command! Date call PutDate()
function! PutDate()
	:put =strftime('%Y-%m-%d')
endfunction


" php pman under cursor
autocmd BufNewFile,BufRead *.php,*.phtml nnoremap <buffer> K :!pman <cword><cr>




"---------------------------
" syntax highlight unfucking
"---------------------------


" :Ss command to fix syntax highlighting problems
command! Ss call SyntaxSyncFromStart()
function! SyntaxSyncFromStart()
	syntax sync fromstart
endfunction

" better default for certain file types; spend more cycles on syntax
" highlighting (not sure it's a good idea to enable this for ALL files because
" some documents are just degenerate to say the least)
autocmd BufNewFile,BufRead *.go,*.c,*.js syntax sync minlines=25000



" ----------------
" holy war follows
" ----------------
command! Ts call SwitchToTabIsSpaces()
command! Ts4 call SwitchToTabIsSpaces()
function! SwitchToTabIsSpaces()
	set shiftwidth=4
	set tabstop=13
	set softtabstop=4
	set expandtab
endfunction

command! Ts2 call SwitchToTabIsSpacesWidth2()
function! SwitchToTabIsSpacesWidth2()
	set shiftwidth=2
	set tabstop=13
	set softtabstop=2
	set expandtab
endfunction

command! Tt call SwitchToTabIsTabs()
command! Tt8 call SwitchToTabIsTabs()
function! SwitchToTabIsTabs()
	set shiftwidth=8
	set tabstop=8
	set softtabstop=0
	set noexpandtab
endfunction

command! Tt4 call SwitchToTabIsTabsWidth4()
function! SwitchToTabIsTabsWidth4()
	set shiftwidth=4
	set tabstop=4
	set softtabstop=0
	set noexpandtab
endfunction
