#!/usr/bin/env bash
set -e
T=build3.js
ls -l song3.js player3.js player3.css player3.doc.html
uglifyjs --rename worklet3.js > worklet3.min.js
node mcomp3.js > $T
uglifyjs --rename player3.js >> $T
uglifyjs --rename song3.js >> $T
ls -l $T

H=build3.html
echo "<!DOCTYPE html>" > $H
echo "<head><script>" >> $H
cat $T >> $H
echo "</script></head>" >> $H
ls -l $H

rm -f $H.gz
gzip -k $H
ls -l $H.gz
