#!/bin/bash
DEV=wlp2s0
ESSID=${1-veralini}
echo "ESSID: '$ESSID'"
killall wpa_supplicant dhcpcd
ifdown $DEV
iwconfig $DEV essid "$ESSID"
wpa_supplicant -Dwext -i$DEV -c/etc/wpa_supplicant/wpa_supplicant.conf -B -f /var/log/wpa_supplicant.log
sleep 2
dhcpcd $DEV
iwlist $DEV channel
