TARGET= controller
ARDUINO_BOARD= mega
#ARDUINO_VARIANT= mega
MCU= atmega2560
ARDUINO_MK_DIR= /usr/local/arduino-bsd-mk
MAKEOBJDIRPREFIX=/usr/obj
#ARDUINO_CFLAGS+= -Wall -Werror -Wstrict-prototypes
#ARDUINO_CXXFLAGS+= -Wall -Werror -Wstrict-prototypes
ARDUINO_CFLAGS+= -Wall
#ARDUINO_CXXFLAGS+= -Wall
.include "${ARDUINO_MK_DIR}/bsd.arduino.mk"

