#!/usr/bin/env bash
set -e
T=build3.js
ls -l song3.js player3.js player3.css player3.doc.html
node mcomp3.js > $T
uglifyjs \
	--rename \
	player3.js >> $T
uglifyjs \
	--rename \
	song3.js >> $T
ls -l $T
rm -f $T.gz
gzip -k $T
ls -l $T.gz
