CFLAGS=-O2
#CFLAGS=-O0 -g
LDLIBS=-lm

bin=lattice lattice3d lattice4 lattice5 lattice6 lattice6f lattice7 lattice8 lattice9 lattice10 lattice11 sinsin sinsin2 sinsin3 lattice12
all: $(bin)

clean:
	rm -f $(bin) *.wav
